# Before you change anything in this file get an idea what it does and read
# - https://about.gitlab.com/blog/2020/12/10/basics-of-gitlab-ci-updated/
# - artifacts https://docs.gitlab.com/ee/ci/jobs/job_artifacts.html

stages:
  - build
 # - test
  - publish

variables: 
  # must be a public project to be accessible by ci
  DOCKER_REGISTRY: "registry.code.fbi.h-da.de/hci-trapp-public/hci-docker/stud_project_builder:latest" 

# Jobs

build-web-app:
  stage: build
  image:
    name: ${DOCKER_REGISTRY}
  before_script:
    - cd app
    - flutter clean
    - flutter doctor
    - flutter upgrade --force
    - flutter config --enable-web
    - flutter pub get
  script:
    - flutter build web --base-href /app/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  artifacts:
    paths:
      - app/build/web

build-apk:
  stage: build
  image:
    name: ${DOCKER_REGISTRY}
  before_script:
    - cd app
    - flutter clean
    - flutter doctor
    - flutter upgrade --force
    - flutter pub get
  script:
    - flutter build apk --release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - app/**/*
      allow_failure: true
  artifacts:
    paths:
      - app/build/app/outputs/flutter-apk/app-release.apk

build-mkdocs:
  stage: build
  image:
    name: ${DOCKER_REGISTRY}
  before_script:
    - mkdocs --version
  script:
    - mkdocs build --strict --verbose
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  artifacts:
    paths:
      - public/docs

# see https://pub.dev/packages/flutter_analyze_reporter/example
# code-quality:
#   stage: test
#   image:
#     name: ${DOCKER_REGISTRY}
#   before_script:
#     - cd app
#     - export PATH="$PATH":"$HOME/.pub-cache/bin"
#   script:
#     - flutter pub get
#     - flutter analyze
#     - dart pub global activate flutter_analyze_reporter
#     - flutter_analyze_reporter --output report.json --reporter gitlab
#   rules:
#     - changes:
#         - app/**/*
#       allow_failure: true
#   artifacts:
#     reports:
#       codequality: app/report.json

# riverpod:
#   stage: test
#   image:
#     name: ${DOCKER_REGISTRY}
#   before_script:
#     - cd app
#   script:
#     - flutter pub get
#     - dart run custom_lint
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"
#       changes:
#         - app/**/*
#   allow_failure: true

pages:
  stage: publish
  script:
    # copy the web-app to public only if it exists, i.e. app/build/web/index.html exists (test: https://linuxhandbook.com/bash-test-command/)
    - test -f app/build/web/index.html && cp -r -v app/build/web public/app || true
  needs:
    - job: build-mkdocs
    - job: build-web-app
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  artifacts:
    paths:
      - public
