site_name: Travel App
#site_url: @ToDo adapt to your project https://hci-trapp.h-da.io/sose24-hci-lab-base-project/pages
site_url: https://hcimo4x-grey-trapp-hci-trapp-hci-lab-studi-sose2-e6afe3a1eb2adc.h-da.io/
site_dir: public/docs
docs_dir: ./docs

plugins:
  - search
  - bibtex:
      bib_file: "docs/assets/lit.bib"
  - autorefs
  - mermaid2

nav:
  - Home: index.md
  - User Research: 
    - user-research/index.md
    - Interview Guide: user-research/interview-guide.md
    - NZSE User Research: user-research/nzse-user-research.md
    - Survey: user-research/survey-evaluation.md
    - Interviews: user-research/interviews.md
    - Personas: user-research/personas.md
    - Requirement Engineering: user-research/requirement-engineering.md
    - User Evaluation: user-research/user-evaluation.md
  - Design: 3-Design.md
  - Implementation: 4-Implementation.md
  - Usability Evaluation: 6-UsabilityEvaluation.md
  - Mkdocs Modules: test.md

theme:
  logo: https://fbi.h-da.de/Cms/Resources/Public/Design/i-lgo.svg
  favicon: https://fbi.h-da.de/typo3conf/ext/hda/Resources/Public/Icons/favicon.ico
  name: "material"
  language: "en" # change to de if you write in German
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.path
    - navigation.expand
    - toc.follow
    - content.code.copy

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: true
  - toc:
      permalink: false
  - meta # needed for search
  - md_in_html # for better formatting of images, e.g. use figure
  - footnotes # for bibtex
  - attr_list # needed by the following for emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.min.js


