import 'package:flutter/material.dart';

// List of checklist suggestions
final List<String> suggestions = [
  'Alarm clock',
  'Aspirin',
  'Backpack',
  'Bandages',
  'Bathing suit',
  'Batteries',
  'Belt',
  'Book',
  'Bottle opener',
  'Camera',
  'Cash',
  'Charging cable',
  'Clothes',
  'Contact lenses',
  'Credit card',
  'Deodorant',
  'Driver’s license',
  'Earplugs',
  'E-reader',
  'Emergency contact list',
  'Flashlight',
  'Flip flops',
  'Fork',
  'Gloves',
  'Hairbrush',
  'Hairdryer',
  'Handbag',
  'Headphones',
  'Health insurance card',
  'Hiking boots',
  'iPad',
  'iPhone',
  'Keychain',
  'Keys',
  'Knife',
  'Laptop',
  'Luggage',
  'Luggage tag',
  'Map',
  'Memory card',
  'Passport',
  'Passport photos',
  'Pen',
  'Perfume',
  'ID',
  'Phone',
  'Raincoat',
  'Razor',
  'Sandals',
  'Scarf',
  'Shampoo',
  'Shoes',
  'Shorts',
  'Shower gel',
  'SIM card',
  'Sleepwear',
  'Socks',
  'Sports equipment',
  'Suitcase',
  'Sunglasses',
  'Sunscreen',
  'Swimsuit',
  'Tablet',
  'Tissues',
  'Toothbrush',
  'Toothpaste',
  'Towel',
  'Trousers',
  'Umbrella',
  'Underwear',
  'USB cable',
  'Walking shoes',
  'Wallet',
  'Watch',
  'Water',
  'Travel insurance',
  'Safety pins',
  'Sunglass case',
];

// Map of checklist items to their corresponding icons
final Map<String, IconData> iconMap = {
  'Alarm clock': Icons.alarm,
  'Aspirin': Icons.healing,
  'Backpack': Icons.backpack,
  'Bandages': Icons.local_hospital,
  'Bathing suit': Icons.beach_access,
  'Batteries': Icons.battery_full,
  'Belt': Icons.accessibility,
  'Book': Icons.book,
  'Bottle opener': Icons.kitchen,
  'Camera': Icons.camera,
  'Cash': Icons.money,
  'Charging cable': Icons.power,
  'Clothes': Icons.checkroom,
  'Contact lenses': Icons.remove_red_eye,
  'Credit card': Icons.credit_card,
  'Deodorant': Icons.brush,
  'Driver’s license': Icons.card_membership,
  'Earplugs': Icons.hearing,
  'E-reader': Icons.tablet,
  'Emergency contact list': Icons.contact_phone,
  'Flashlight': Icons.flashlight_on,
  'Flip flops': Icons.waves,
  'Fork': Icons.restaurant,
  'Gloves': Icons.back_hand,
  'Hairbrush': Icons.brush,
  'Hairdryer': Icons.air,
  'Handbag': Icons.shopping_bag,
  'Headphones': Icons.headphones,
  'Health insurance card': Icons.health_and_safety,
  'Hiking boots': Icons.hiking,
  'iPad': Icons.tablet_mac,
  'iPhone': Icons.phone_iphone,
  'Keychain': Icons.vpn_key,
  'Keys': Icons.vpn_key,
  'Knife': Icons.local_dining,
  'Laptop': Icons.laptop,
  'Luggage': Icons.luggage,
  'Luggage tag': Icons.tag,
  'Map': Icons.map,
  'Memory card': Icons.sd_card,
  'Passport': Icons.travel_explore,
  'Passport photos': Icons.photo,
  'Pen': Icons.edit,
  'Perfume': Icons.spa,
  'ID': Icons.card_membership,
  'Phone': Icons.phone,
  'Raincoat': Icons.umbrella,
  'Razor': Icons.content_cut,
  'Sandals': Icons.beach_access,
  'Scarf': Icons.checkroom,
  'Shampoo': Icons.local_hospital,
  'Shoes': Icons.shopping_bag,
  'Shorts': Icons.checkroom,
  'Shower gel': Icons.local_hospital,
  'SIM card': Icons.sim_card,
  'Sleepwear': Icons.bedtime,
  'Socks': Icons.checkroom,
  'Sports equipment': Icons.sports,
  'Suitcase': Icons.luggage,
  'Sunglasses': Icons.wb_sunny,
  'Sunscreen': Icons.wb_sunny,
  'Swimsuit': Icons.beach_access,
  'Tablet': Icons.tablet,
  'Tissues': Icons.announcement,
  'Toothbrush': Icons.brush,
  'Toothpaste': Icons.local_hospital,
  'Towel': Icons.beach_access,
  'Trousers': Icons.checkroom,
  'Umbrella': Icons.umbrella,
  'Underwear': Icons.checkroom,
  'USB cable': Icons.usb,
  'Walking shoes': Icons.hiking,
  'Wallet': Icons.account_balance_wallet,
  'Watch': Icons.watch,
  'Water': Icons.water,
  'Travel insurance': Icons.card_travel,
  'Safety pins': Icons.safety_check,
  'Sunglass case': Icons.wb_sunny,
};
