name: ri_go_demo
description: A demo project, that uses riverpod and go_router.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  intl: ^0.18.1
  # riverpod stuff
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  dio: ^5.4.2+1
  pretty_dio_logger: ^1.3.1
  logger: ^2.2.0
  go_router: ^13.2.2
  gap: ^3.0.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  very_good_analysis: ^5.1.0
  # riverpod generator/dev stuff
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  
flutter:
  uses-material-design: true
  # for localization
  generate: true
